apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-readiness
  labels:
    app: demo-readiness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-readiness
  template:
    metadata:
      labels:
        app: demo-readiness
    spec:
      containers:
      - name: demo-container
        image: gcr.io/google-samples/simple-app:1.0
        ports:
        - containerPort: 8080
        readinessProbe:  # 就绪探针，决定是否接收流量
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
---
# 暴露为服务
apiVersion: v1
kind: Service
metadata:
  name: demo-readiness-service
spec:
  selector:
    app: demo-readiness
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP