apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: demos.example.com
  labels:
    app: demo-operator
spec:
  group: example.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              size:
                type: integer
                minimum: 1
                maximum: 10
              image:
                type: string
                default: nginx:latest
            required:
            - size
  scope: Namespaced
  names:
    plural: demos
    singular: demo
    kind: Demo
    shortNames:
    - dmo
