apiVersion: v1
kind: Namespace
metadata:
  name: zipkin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zipkin
  namespace: zipkin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zipkin
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zipkin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zipkin
subjects:
- kind: ServiceAccount
  name: zipkin
  namespace: zipkin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      serviceAccountName: zipkin
      containers:
      - name: zipkin
        image: openzipkin/zipkin:2.24.3
        env:
        - name: STORAGE_TYPE
          value: mem
        - name: ZIPKIN_UI_LOGS_URL
          value: ""
        ports:
        # Zipkin UI and API
        - containerPort: 9411
          name: zipkin-ui
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: zipkin
spec:
  type: NodePort
  selector:
    app: zipkin
  ports:
  - name: zipkin-ui
    port: 9411
    targetPort: 9411
    nodePort: 30069
